### ISSUE TITLE
wx object is NoneType

### ISSUE THREAD

**Issue by KarlZeilhofer** [HiGregSmith/LayerViewSet#1]
Hi, 
I just tried your plugin on Linux Mint 18.1 with the nightly KiCad. 
I get this message, when I click on the menu entry: 

![2018-05-05_003](https://user-images.githubusercontent.com/2773445/39663936-ed05f390-507b-11e8-8819-f9fd53012882.png)

Do you have any ideas, what I can do about it?

Greets, 
Karl

To make the text searchable:
```
Traceback (most recent call last):

  File "/usr/share/kicad/scripting/plugins/layerviewset.py", line 390, in Run
    wx.GetTopLevelWindows()

AttributeError: 'NoneType' object has no attribute 'GetTopLevelWindows'
```

**Comment by HiGregSmith** [comment]
What version of KiCad are you using (and version of wxPython)?

I should be able to look at this in about 12 hours.

**Comment by HiGregSmith** [comment]
I just saw "nightly" so that answers that question. What about wxPython version?

**Comment by HiGregSmith** [comment]
I downloaded today's windows nightly and had to fix one of the constants from pcbnew. But I don't get the error you see regarding "wx" as NoneType. It seems like something is wrong with "import wx" but I'm not sure why there isn't an error on the "import wx" line.

**Comment by HiGregSmith** [comment]
Also uploaded a fix to the name/save function.

**Comment by HiGregSmith** [comment]
I have one windows user that had the same error as you reporting that the updated LayerViewSet works for them. Does this fix the issue in Linux?

**Comment by HiGregSmith** [comment]
I duplicated the error by initiating LayerViewSet from the External Tools menu. It failed with the same error message you report. I've uploaded a fix for this.

**Comment by KarlZeilhofer** [comment]
That problem seems to be fixed now, but I got a new one.
